<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Jan 19: ASSIGNMENT Estimating the geometric growth rate | BIOL 3295: Population and Evolutionary Ecology, Winter 2023</title>
  <meta name="description" content="8 Jan 19: ASSIGNMENT Estimating the geometric growth rate | BIOL 3295: Population and Evolutionary Ecology, Winter 2023" />
  <meta name="generator" content="bookdown 0.30 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Jan 19: ASSIGNMENT Estimating the geometric growth rate | BIOL 3295: Population and Evolutionary Ecology, Winter 2023" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Jan 19: ASSIGNMENT Estimating the geometric growth rate | BIOL 3295: Population and Evolutionary Ecology, Winter 2023" />
  
  
  

<meta name="author" content="Amy Hurford" />


<meta name="date" content="2023-01-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pheasant.html"/>
<link rel="next" href="partI.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Syllabus</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#instructor-information"><i class="fa fa-check"></i><b>1.1</b> Instructor Information</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#course-information"><i class="fa fa-check"></i><b>1.2</b> Course Information</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#method-of-evaluation"><i class="fa fa-check"></i><b>1.3</b> Method of Evaluation</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#additional-policies"><i class="fa fa-check"></i><b>1.4</b> Additional Policies</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#accommodation-of-students-with-disabilities"><i class="fa fa-check"></i><b>1.4.1</b> Accommodation of students with disabilities</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#academic-misconduct"><i class="fa fa-check"></i><b>1.4.2</b> Academic misconduct</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#equity-and-diversity"><i class="fa fa-check"></i><b>1.4.3</b> Equity and Diversity</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#additional-supports"><i class="fa fa-check"></i><b>1.5</b> Additional Supports</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a></li>
<li class="chapter" data-level="3" data-path="jan-5-introduction.html"><a href="jan-5-introduction.html"><i class="fa fa-check"></i><b>3</b> Jan 5: Introduction</a>
<ul>
<li class="chapter" data-level="3.1" data-path="jan-5-introduction.html"><a href="jan-5-introduction.html#some-questions"><i class="fa fa-check"></i><b>3.1</b> Some questions</a></li>
<li class="chapter" data-level="3.2" data-path="jan-5-introduction.html"><a href="jan-5-introduction.html#references"><i class="fa fa-check"></i><b>3.2</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="jan-6-discrete-and-continous-variables.html"><a href="jan-6-discrete-and-continous-variables.html"><i class="fa fa-check"></i><b>4</b> Jan 6: Discrete and continous variables</a></li>
<li class="chapter" data-level="5" data-path="jan-12-assignment-rmarkdown-and-tidyverse.html"><a href="jan-12-assignment-rmarkdown-and-tidyverse.html"><i class="fa fa-check"></i><b>5</b> Jan 12: <strong>ASSIGNMENT</strong> Rmarkdown and tidyverse</a></li>
<li class="chapter" data-level="6" data-path="jan-13-geometric-growth.html"><a href="jan-13-geometric-growth.html"><i class="fa fa-check"></i><b>6</b> Jan 13: Geometric growth</a>
<ul>
<li class="chapter" data-level="6.1" data-path="jan-13-geometric-growth.html"><a href="jan-13-geometric-growth.html#reading"><i class="fa fa-check"></i><b>6.1</b> Reading</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="pheasant.html"><a href="pheasant.html"><i class="fa fa-check"></i><b>7</b> Jan 17: Geometric growth</a>
<ul>
<li class="chapter" data-level="7.1" data-path="pheasant.html"><a href="pheasant.html#reading-1"><i class="fa fa-check"></i><b>7.1</b> Reading</a></li>
<li class="chapter" data-level="7.2" data-path="pheasant.html"><a href="pheasant.html#questions"><i class="fa fa-check"></i><b>7.2</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="estimate.html"><a href="estimate.html"><i class="fa fa-check"></i><b>8</b> Jan 19: <strong>ASSIGNMENT</strong> Estimating the geometric growth rate</a>
<ul>
<li class="chapter" data-level="8.1" data-path="estimate.html"><a href="estimate.html#code"><i class="fa fa-check"></i><b>8.1</b> Code</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="estimate.html"><a href="estimate.html#loading-and-plotting-the-data"><i class="fa fa-check"></i><b>8.1.1</b> Loading and plotting the data</a></li>
<li class="chapter" data-level="8.1.2" data-path="estimate.html"><a href="estimate.html#function-for-geometric-growth"><i class="fa fa-check"></i><b>8.1.2</b> Function for geometric growth</a></li>
<li class="chapter" data-level="8.1.3" data-path="estimate.html"><a href="estimate.html#fitting-lambda"><i class="fa fa-check"></i><b>8.1.3</b> Fitting lambda</a></li>
<li class="chapter" data-level="8.1.4" data-path="estimate.html"><a href="estimate.html#plotting-the-fit"><i class="fa fa-check"></i><b>8.1.4</b> Plotting the fit</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="estimate.html"><a href="estimate.html#to-hand-in"><i class="fa fa-check"></i><b>8.2</b> To hand in</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIOL 3295: Population and Evolutionary Ecology, Winter 2023</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimate" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Jan 19: <strong>ASSIGNMENT</strong> Estimating the geometric growth rate<a href="estimate.html#estimate" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>ASSIGNMENT 2 due Jan 26.</p>
<p>You are to write an Rmarkdown report that estimates the geometric growth rate, <span class="math inline">\(\lambda\)</span>, for the <a href="pheasant.html#pheasant">Protection Island pheasant population</a>. Your report needs to consider two methods for estimating the geometric growth rate: fitting; and estimation from independent data.</p>
<p>The code you will need to complete this assignment is below. You may copy and paste this code into your Rmarkdown report. Sometimes you will need to change the values.</p>
<p>The requirements of the report follow the code.</p>
<div id="code" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Code<a href="estimate.html#code" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="loading-and-plotting-the-data" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Loading and plotting the data<a href="estimate.html#loading-and-plotting-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Load the data. I copied the data on to a website, so it can be loaded with the command below. Click <a href="https://github.com/ahurford/biol-4605-data/blob/main/data/protection-island.csv">here</a> to view the code on the website.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="estimate.html#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/ahurford/biol-4605-data/main/data/protection-island.csv&quot;</span>)</span></code></pre></div>
<p>Let’s plot the data. We select only columns 1 and 2 of the data because column 3 contains comments. We plot <code>year</code> on the horizontal (x-) axis and <code>size</code> on the (y-) vertical axis.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="estimate.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(ggplot2)</span>
<span id="cb2-2"><a href="estimate.html#cb2-2" aria-hidden="true" tabindex="-1"></a>protection.island <span class="ot">&lt;-</span> data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb2-3"><a href="estimate.html#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="estimate.html#cb2-4" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">=</span> <span class="fu">ggplot</span>(<span class="at">data =</span> protection.island, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> size)) <span class="sc">+</span> </span>
<span id="cb2-5"><a href="estimate.html#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-6"><a href="estimate.html#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;year&quot;</span>)<span class="sc">+</span></span>
<span id="cb2-7"><a href="estimate.html#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;population size&quot;</span>)<span class="sc">+</span></span>
<span id="cb2-8"><a href="estimate.html#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Protection Island&quot;</span>)</span>
<span id="cb2-9"><a href="estimate.html#cb2-9" aria-hidden="true" tabindex="-1"></a>g1</span></code></pre></div>
<p><img src="BIOL-3295_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="function-for-geometric-growth" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Function for geometric growth<a href="estimate.html#function-for-geometric-growth" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Below is the definition of a geometric growth function with time, <span class="math inline">\(t\)</span>, specifically defined for the number of years of Protection Island pheasant data, and the initial population size, <span class="math inline">\(N_0\)</span>, defined specifically for the Protection Island data. You need to give this function in your code <em>before</em> you call the function.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="estimate.html#cb3-1" aria-hidden="true" tabindex="-1"></a>geo.pred <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda){</span>
<span id="cb3-2"><a href="estimate.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">=</span> protection.island<span class="sc">$</span>year <span class="sc">-</span> protection.island<span class="sc">$</span>year[<span class="dv">1</span>]</span>
<span id="cb3-3"><a href="estimate.html#cb3-3" aria-hidden="true" tabindex="-1"></a>  N0 <span class="ot">=</span> protection.island<span class="sc">$</span>size[<span class="dv">1</span>]</span>
<span id="cb3-4"><a href="estimate.html#cb3-4" aria-hidden="true" tabindex="-1"></a>  size <span class="ot">=</span> N0<span class="sc">*</span>lambda<span class="sc">^</span>t</span>
<span id="cb3-5"><a href="estimate.html#cb3-5" aria-hidden="true" tabindex="-1"></a>  pred <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">year =</span> protection.island<span class="sc">$</span>year, <span class="at">size =</span> size)</span>
<span id="cb3-6"><a href="estimate.html#cb3-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The function is called by running <code>geo.pred(lambda)</code> in the console, where you enter a specific numerical value for <code>lambda</code>.</p>
<p>After you have run the code (i.e. in the Console) that defines the <code>geo.pred(lambda)</code> function (above), try <code>lambda = 3</code> as:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="estimate.html#cb4-1" aria-hidden="true" tabindex="-1"></a>result <span class="ot">=</span> <span class="fu">geo.pred</span>(<span class="dv">3</span>)</span>
<span id="cb4-2"><a href="estimate.html#cb4-2" aria-hidden="true" tabindex="-1"></a>result</span></code></pre></div>
<pre><code>##   year size
## 1 1936   10
## 2 1937   30
## 3 1938   90
## 4 1939  270</code></pre>
<p>Remember, negative values of <code>lambda</code> are non-sensical. (<em>For what values of <code>lambda</code> (or <span class="math inline">\(\lambda\)</span>), does the population grow, again? Not sure? You can try some values in the <code>geo.pred(lambda)</code> function to figure this out by experimentation.</em>)</p>
<p><strong>Question 1</strong> The <code>geo.pred()</code> function works by running the lines of code inside the <code>geo.pred()</code> function definition for the value of <code>lambda</code> that you supply (inside the parentheses in the function call). In the function definition, what are the lines of code that are pasted below doing? (Hint: What is the data frame <code>protection.island</code>? Note that <code>data[1]</code> selects the first value of a list of values and the <code>$</code> selects a particular column of a data frame).</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="estimate.html#cb6-1" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">=</span> protection.island<span class="sc">$</span>year <span class="sc">-</span> protection.island<span class="sc">$</span>year[<span class="dv">1</span>]</span>
<span id="cb6-2"><a href="estimate.html#cb6-2" aria-hidden="true" tabindex="-1"></a>  N0 <span class="ot">=</span> protection.island<span class="sc">$</span>size[<span class="dv">1</span>]</span></code></pre></div>
</div>
<div id="fitting-lambda" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Fitting lambda<a href="estimate.html#fitting-lambda" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We have defined a function that will predict the population size of pheasants on Protection Island for different user supplied values of <code>lambda</code>. But what value of <code>lambda</code> is most likely given the data?</p>
<p>To answer this question we will use a statistical method known as maximum likelihood.</p>
<p>Our first step is to define a function that quantifies the fit of a given <code>lambda</code> value. This function assumes that deviations of the recorded data from the model-predicted values follow a Poisson distribution:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="estimate.html#cb7-1" aria-hidden="true" tabindex="-1"></a>geofit <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda){</span>
<span id="cb7-2"><a href="estimate.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  pred<span class="ot">=</span><span class="fu">geo.pred</span>(<span class="at">lambda=</span>lambda)</span>
<span id="cb7-3"><a href="estimate.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  Ypred <span class="ot">=</span> pred<span class="sc">$</span>size</span>
<span id="cb7-4"><a href="estimate.html#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dpois</span>(protection.island<span class="sc">$</span>size, Ypred, <span class="at">log=</span>T))</span>
<span id="cb7-5"><a href="estimate.html#cb7-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>After running the <code>geo.fit(lambda)</code> function (in the Console), lets try to use the function and get some values of the negative log likelihood (i.e. the fit):</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="estimate.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geofit</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 41.64846</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="estimate.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geofit</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 1280.129</code></pre>
<p>This result tells us that given the data, <code>lambda = 3</code> is much more likely than <code>lambda = 1</code> because the negative log likelihood value (41.65) is much smaller.</p>
<p>But what value of <code>lambda</code> is most likelihood given the data? Equivalently, for what value of <code>lambda</code> is the negative log likelihood minimized? To answer this question we need to call a function that will perform an optimization. This requires the <code>mle2</code> function from the <code>bbmle</code> package, and you will need to install this package prior to using this function.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="estimate.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bbmle)</span></code></pre></div>
<pre><code>## Loading required package: stats4</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="estimate.html#cb14-1" aria-hidden="true" tabindex="-1"></a>fit.geo <span class="ot">&lt;-</span> <span class="fu">mle2</span>(geofit, <span class="at">start=</span><span class="fu">list</span>(<span class="at">lambda=</span><span class="dv">3</span>))</span>
<span id="cb14-2"><a href="estimate.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.geo)</span></code></pre></div>
<pre><code>## Maximum likelihood estimation
## 
## Call:
## mle2(minuslogl = geofit, start = list(lambda = 3))
## 
## Coefficients:
##        Estimate Std. Error z value     Pr(z)    
## lambda 3.408974   0.053472  63.752 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## -2 log L: 24.32396</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="estimate.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit.geo)</span></code></pre></div>
<pre><code>##    2.5 %   97.5 % 
## 3.304256 3.513845</code></pre>
<p>The output above tells us that the maximum likelihood estimate of <code>lambda</code> is 3.41 and that the 95% confidence interval is [3.30, 3.51].</p>
</div>
<div id="plotting-the-fit" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Plotting the fit<a href="estimate.html#plotting-the-fit" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we would like to use our estimate values of <code>lambda</code> in the geometric growth function and compare the fitted values with the observed data.</p>
<p>In the code below, <code>lambda = 3</code> is the estimated lambda value, and the 95% confidence interval is [2,4] (as example values). To use this code for your assignment you will need to substitute different values.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="estimate.html#cb18-1" aria-hidden="true" tabindex="-1"></a>fit.predictions <span class="ot">=</span> <span class="fu">geo.pred</span>(<span class="dv">3</span>)<span class="sc">$</span>size</span>
<span id="cb18-2"><a href="estimate.html#cb18-2" aria-hidden="true" tabindex="-1"></a>lower.fit <span class="ot">=</span> <span class="fu">geo.pred</span>(<span class="dv">2</span>)<span class="sc">$</span>size</span>
<span id="cb18-3"><a href="estimate.html#cb18-3" aria-hidden="true" tabindex="-1"></a>upper.fit <span class="ot">=</span> <span class="fu">geo.pred</span>(<span class="dv">4</span>)<span class="sc">$</span>size</span></code></pre></div>
<p>We had already made a plot of the data and we named our graph <code>g1</code>. We can now add some more layers to the graph as shown below. Note that the line is the value of <code>fit.predictions</code> as defined above (i.e., set <code>=3</code> as an example), and the shaded ribbon spans from <code>lower.fit</code> to <code>upper.fit</code> (i.e., set to <code>2</code> and <code>4</code> as an example).</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="estimate.html#cb19-1" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">=</span> g1 <span class="sc">+</span></span>
<span id="cb19-2"><a href="estimate.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>fit.predictions)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="estimate.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower.fit, <span class="at">ymax =</span> upper.fit), <span class="at">alpha =</span> .<span class="dv">2</span>)</span></code></pre></div>
<p>(The value of <code>alpha = 0.2</code> makes the ribbon transparent)</p>
</div>
</div>
<div id="to-hand-in" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> To hand in<a href="estimate.html#to-hand-in" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Answer Question 1 which appears in bold in the <em>Function for geometric growth</em> section. [3 marks]</p></li>
<li><p>Write an Rmarkdown report that estimates <span class="math inline">\(\lambda\)</span> (i.e. <code>lambda</code>) in the geometric growth rate function using maximum likelihood fitting.</p></li>
</ol>
<p>You must include a graph that shows:</p>
<ul>
<li><p>The data (shown as dots);</p></li>
<li><p>The predicted values for the maximum likelihood estimate of <code>lambda</code> (shown as a line);</p></li>
<li><p>The predicted values for the 95% confidence interval for the estimate of <code>lambda</code> (shown as a shaded region);</p></li>
</ul>
<p>You must include a figure caption that explains the main point of your graph, and what the symbols are.</p>
<p>Your Rmarkdown file must contain a sequence of R commands that produces the graph. [10 marks]</p>
<ol start="3" style="list-style-type: decimal">
<li>Estimate <span class="math inline">\(\lambda\)</span> from data independent of the time series describing the population size of pheasants on Protection Island. This means that you cannot use more than one value of the population size to estimate one value of a quantity (you should be using the population size in a given year to calculate per capita rates by dividing only). You goal is to keep your parameter estimation method independent from the time series of pheasant population size so that you can <em>validate</em> the assumptions of your geometric growth model. In your Rmarkdown report you should:</li>
</ol>
<ul>
<li><p>Derive a formula for <span class="math inline">\(\lambda\)</span> in terms of <span class="math inline">\(b\)</span>, the per capita birth rate, and the probability of mortality <span class="math inline">\(d\)</span> each year. Do this based on the class discussion on January 17 or by reading <a href="https://ebookcentral.proquest.com/lib/mun/reader.action?docID=768551&amp;ppg=29">Otto and Day, 2007</a> <em>Section 2.5.1 Discrete-Time Models</em> p47-50 and omit migration (i.e. <span class="math inline">\(m=0\)</span>) for the application to the Protection Island pheasant population. [2 marks]</p></li>
<li><p>State some important assumptions of your <span class="math inline">\(\lambda\)</span> formula. [3 marks]</p></li>
<li><p>Estimate <span class="math inline">\(b\)</span> and <span class="math inline">\(d\)</span> using some of the information given <a href="pheasant.html#pheasant">here</a>. State assumptions that you have made when data is lacking or information is contradictory. Calculate <span class="math inline">\(\lambda\)</span> given the formula you derived. [4 marks]</p></li>
<li><p>Use the <code>geo.pred(lambda)</code> function to predict the population size of pheasants on Protection Island for your independently estimated <span class="math inline">\(\lambda\)</span> value. The code to do this must be included in your Rmarkdown file. [2 marks]</p></li>
<li><p>Make a plot of your predictions relative to the reported data. Include a figure caption that describes the main point of your figure and defines all the symbols. [3 marks]</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pheasant.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="partI.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOL-3295.epub"],
"search": {
"engine": "fuse",
"options": null
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
